package frontend.visual_designers;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author lorin
 */
public class VisualInsertDesigner extends javax.swing.JPanel {
    private final int DEFAULT_ROW_COUNT = 10;

    // References
    private final DefaultTableModel tableModel;

    public VisualInsertDesigner() {
        initComponents();

        // Init table model
        this.tableModel = new DefaultTableModel();
        this.insertTable.setModel(this.tableModel);

        this.setColumnsAndRowCount(new ArrayList<>(){{
            add("Elso");
            add("Masodik");
            add("Harmadik");
        }}, DEFAULT_ROW_COUNT);
    }

    private void setColumnsAndRowCount(ArrayList<String> columnNames, int rowCount) {
        this.tableModel.setColumnIdentifiers(columnNames.toArray());
        this.tableModel.setRowCount(rowCount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateCodeButton = new javax.swing.JButton();
        tabelNameLabel = new javax.swing.JLabel();
        splitInsertPanel = new javax.swing.JSplitPane();
        tableScrollPanel = new javax.swing.JScrollPane();
        insertTable = new javax.swing.JTable();
        generatedCodeScrollPanel = new javax.swing.JScrollPane();
        generatedCodeTextArea = new javax.swing.JTextArea();
        tableSelectComboBox = new javax.swing.JComboBox<>();

        generateCodeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateCodeButton.setText("Generate Code");

        tabelNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelNameLabel.setText("Table Name:");

        splitInsertPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        insertTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertTable.setForeground(new java.awt.Color(255, 51, 0));
        insertTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        insertTable.setInheritsPopupMenu(true);
        insertTable.setName(""); // NOI18N
        insertTable.setShowGrid(true);
        tableScrollPanel.setViewportView(insertTable);

        splitInsertPanel.setTopComponent(tableScrollPanel);

        generatedCodeTextArea.setEditable(false);
        generatedCodeTextArea.setColumns(20);
        generatedCodeTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generatedCodeTextArea.setRows(5);
        generatedCodeScrollPanel.setViewportView(generatedCodeTextArea);

        splitInsertPanel.setRightComponent(generatedCodeScrollPanel);

        tableSelectComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "table_1", "table_2", "table_3", "table_4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(splitInsertPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateCodeButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tabelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitInsertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateCodeButton;
    private javax.swing.JScrollPane generatedCodeScrollPanel;
    private javax.swing.JTextArea generatedCodeTextArea;
    private javax.swing.JTable insertTable;
    private javax.swing.JSplitPane splitInsertPanel;
    private javax.swing.JLabel tabelNameLabel;
    private javax.swing.JScrollPane tableScrollPanel;
    private javax.swing.JComboBox<String> tableSelectComboBox;
    // End of variables declaration//GEN-END:variables
}
