package frontend.visual_designers;

import java.util.ArrayList;

public class VisualDeleteDesigner extends javax.swing.JPanel {
    private int test = 0;

    public VisualDeleteDesigner() {
        initComponents();

        // Set references
        this.selectionPanel.setVisualDeleteDesigner(this);
    }

    /* Setters */
    public void setDividerLocation(int location) {
        if (location > 0 && location < this.splitPanel.getMinimumSize().getHeight()) this.splitPanel.setDividerLocation(location);
    }

    /* Getters */
    public String getSelectedTable() { return (String) this.tableSelectComboBox.getSelectedItem(); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelNameLabel = new javax.swing.JLabel();
        tableSelectComboBox = new javax.swing.JComboBox<>();
        generateCodeButton = new javax.swing.JButton();
        splitPanel = new javax.swing.JSplitPane();
        generatedCodeScrollPanel = new javax.swing.JScrollPane();
        generatedCodeTextArea = new javax.swing.JTextArea();
        selectionPanel = new frontend.visual_designers.visual_elements.FieldSelectionPanelDelete();
        jButton1 = new javax.swing.JButton();

        tabelNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelNameLabel.setText("Table Name:");
        tabelNameLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableSelectComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "table_1", "table_2", "table_3", "table_4" }));
        tableSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableSelectComboBoxActionPerformed(evt);
            }
        });

        generateCodeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateCodeButton.setText("Generate Code");
        generateCodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generateCodeButtonMousePressed(evt);
            }
        });
        generateCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateCodeButtonActionPerformed(evt);
            }
        });

        splitPanel.setDividerLocation(408);
        splitPanel.setDividerSize(3);
        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        generatedCodeTextArea.setEditable(false);
        generatedCodeTextArea.setColumns(20);
        generatedCodeTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generatedCodeTextArea.setRows(5);
        generatedCodeScrollPanel.setViewportView(generatedCodeTextArea);

        splitPanel.setRightComponent(generatedCodeScrollPanel);
        splitPanel.setLeftComponent(selectionPanel);

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(generateCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(splitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateCodeButton)
                    .addComponent(tabelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableSelectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSelectComboBoxActionPerformed

    private void generateCodeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateCodeButtonMousePressed
        // Get SQL command
        String command = this.selectionPanel.getSQLDeleteCommand();

        // Set output text area
        this.generatedCodeTextArea.setText(command);
    }//GEN-LAST:event_generateCodeButtonMousePressed

    private void generateCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateCodeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_generateCodeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           if(test == 0) {
            // Temp
            this.selectionPanel.setFieldPanelData(new ArrayList<>(){{
                                                      add("Column_name1");
                                                      add("Column_name2");
                                                  }},
                    new ArrayList<>(){{
                        add("Table_name1");
                        add("Table_name2");
                    }});
        } else if(test == 1) {
            this.selectionPanel.setFieldPanelData(new ArrayList<>(){{
                                                      add("Column_name1");
                                                      add("Column_name2");
                                                      add("Column_name3");
                                                  }},
                    new ArrayList<>(){{
                        add("Table_name1");
                        add("Table_name2");
                        add("Table_name3");
                    }});
        } else if(test == 2) {
            this.selectionPanel.setFieldPanelData(new ArrayList<>(){{
                                                      add("Column_name1");
                                                      add("Column_name2");
                                                      add("Column_name3");
                                                      add("Column_name4");
                                                  }},
                    new ArrayList<>(){{
                        add("Table_name1");
                        add("Table_name2");
                        add("Table_name3");
                        add("Table_name4");
                    }});
        } else {
                    this.selectionPanel.setFieldPanelData(new ArrayList<>(){{
                                                              add("Column_name1");
                                                              add("Column_name2");
                                                              add("Column_name3");
                                                              add("Column_name4");
                                                              add("Column_name4");
                                                              add("Column_name4");
                                                              add("Column_name4");
                                                              add("Column_name4");
                                                              add("Column_name4");
                                                          }},
                            new ArrayList<>(){{
                                add("Table_name1");
                                add("Table_name2");
                                add("Table_name3");
                                add("Table_name4");
                                add("Table_name4");
                                add("Table_name4");
                                add("Table_name4");
                                add("Table_name4");
                                add("Table_name4");
                            }});
        }
        test++;
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateCodeButton;
    private javax.swing.JScrollPane generatedCodeScrollPanel;
    private javax.swing.JTextArea generatedCodeTextArea;
    private javax.swing.JButton jButton1;
    private frontend.visual_designers.visual_elements.FieldSelectionPanelDelete selectionPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JLabel tabelNameLabel;
    private javax.swing.JComboBox<String> tableSelectComboBox;
    // End of variables declaration//GEN-END:variables
}
