package frontend.visual_designers;

import control.ClientController;
import frontend.center_panel.CenterClientPanel;
import lombok.Setter;

import javax.swing.*;
import java.util.ArrayList;

public class VisualDeleteDesigner extends javax.swing.JPanel {
    // References
    @Setter
    private CenterClientPanel centerClientPanel;

    @Setter
    private ClientController clientController;

    private int test = 0;

    public VisualDeleteDesigner() {
        initComponents();

        // Set references
        this.selectionPanel.setVisualDeleteDesigner(this);
    }

    /* Setters */
    public void setDividerLocation(int location) {
        if (location > 0 && location < this.splitPanel.getMinimumSize().getHeight()) this.splitPanel.setDividerLocation(location);
    }

    public void updateTables() {
        ArrayList<String> tableNames = this.clientController.getCurrentDatabaseTables();

        // Update items in combo box
        this.tableSelectComboBox.removeAllItems();
        for(final String tableName : tableNames) {
            this.tableSelectComboBox.addItem(tableName);
        }
    }

    /* Getters */
    public String getSelectedTable() { return (String) this.tableSelectComboBox.getSelectedItem(); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelNameLabel = new javax.swing.JLabel();
        tableSelectComboBox = new javax.swing.JComboBox<>();
        generateCodeButton = new javax.swing.JButton();
        splitPanel = new javax.swing.JSplitPane();
        generatedCodeScrollPanel = new javax.swing.JScrollPane();
        generatedCodeTextArea = new javax.swing.JTextArea();
        selectionPanel = new frontend.visual_designers.visual_elements.FieldSelectionPanelDelete();
        executeButton = new javax.swing.JButton();

        tabelNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelNameLabel.setText("Table Name:");
        tabelNameLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableSelectComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "table_1", "table_2", "table_3", "table_4" }));
        tableSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableSelectComboBoxActionPerformed(evt);
            }
        });

        generateCodeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateCodeButton.setText("Generate Code");
        generateCodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generateCodeButtonMousePressed(evt);
            }
        });
        generateCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateCodeButtonActionPerformed(evt);
            }
        });

        splitPanel.setDividerLocation(408);
        splitPanel.setDividerSize(3);
        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        generatedCodeTextArea.setEditable(false);
        generatedCodeTextArea.setColumns(20);
        generatedCodeTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generatedCodeTextArea.setRows(5);
        generatedCodeScrollPanel.setViewportView(generatedCodeTextArea);

        splitPanel.setRightComponent(generatedCodeScrollPanel);
        splitPanel.setLeftComponent(selectionPanel);

        executeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        executeButton.setText("Execute");
        executeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                executeButtonMousePressed(evt);
            }
        });
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(executeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateCodeButton)
                    .addComponent(tabelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableSelectComboBoxActionPerformed
        // Get selected index
        String tableName = (String) this.tableSelectComboBox.getSelectedItem();

        // Update selection panel
        ArrayList<String> columnNames = this.clientController.getTableAttributes(tableName);
        ArrayList<String> tableNames = new ArrayList<>();
        for(int i = 0; i < columnNames.size(); ++i) {
            tableNames.add(tableName);
        }
        this.selectionPanel.setFieldPanelData(columnNames, tableNames);
    }//GEN-LAST:event_tableSelectComboBoxActionPerformed

    private void generateCodeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateCodeButtonMousePressed
        // Get SQL command
        String command = this.selectionPanel.getSQLDeleteCommand();

        // Set output text area
        this.generatedCodeTextArea.setText(command);
    }//GEN-LAST:event_generateCodeButtonMousePressed

    private void generateCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateCodeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_generateCodeButtonActionPerformed

    private void executeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_executeButtonMousePressed
        // Get SQL command
        String command = this.selectionPanel.getSQLDeleteCommand();

        // Set command in SQL execution area
        this.centerClientPanel.setInputTextAreaString(command);
        // Switch to that pane
        this.centerClientPanel.setCurrentPane(0);
    }//GEN-LAST:event_executeButtonMousePressed

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeButton;
    private javax.swing.JButton generateCodeButton;
    private javax.swing.JScrollPane generatedCodeScrollPanel;
    private javax.swing.JTextArea generatedCodeTextArea;
    private frontend.visual_designers.visual_elements.FieldSelectionPanelDelete selectionPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JLabel tabelNameLabel;
    private javax.swing.JComboBox<String> tableSelectComboBox;
    // End of variables declaration//GEN-END:variables
}
