package frontend.center_panel;

import control.ClientController;

public class CenterClientPanel extends javax.swing.JPanel {
    private ClientController clientController;

    public CenterClientPanel() {
        initComponents();

        // Set references
        this.commandInputOutputPanel1.setCenterClientPanel(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientTabbedPane = new javax.swing.JTabbedPane();
        sqlCommandExecutionPanel = new javax.swing.JSplitPane();
        commandPanel1 = new frontend.center_panel.CommandPanel();
        commandInputOutputPanel1 = new frontend.center_panel.CommandInputOutputPanel();
        visualInsertDesignerPanel = new frontend.visual_designers.VisualInsertDesigner();
        visualDeleteDesignerPanel = new frontend.visual_designers.VisualDeleteDesigner();
        visualSelectDesignerPanel = new frontend.visual_designers.VisualSelectDesigner();

        clientTabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clientTabbedPane.setMinimumSize(new java.awt.Dimension(900, 900));

        sqlCommandExecutionPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        sqlCommandExecutionPanel.setTopComponent(commandPanel1);
        sqlCommandExecutionPanel.setRightComponent(commandInputOutputPanel1);

        clientTabbedPane.addTab("SQL Command Execution", sqlCommandExecutionPanel);
        clientTabbedPane.addTab("Visual Insert Designer", visualInsertDesignerPanel);

        javax.swing.GroupLayout visualDeleteDesignerPanelLayout = new javax.swing.GroupLayout(visualDeleteDesignerPanel);
        visualDeleteDesignerPanel.setLayout(visualDeleteDesignerPanelLayout);
        visualDeleteDesignerPanelLayout.setHorizontalGroup(
            visualDeleteDesignerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        visualDeleteDesignerPanelLayout.setVerticalGroup(
            visualDeleteDesignerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );

        clientTabbedPane.addTab("Visual Delete Designer", visualDeleteDesignerPanel);

        javax.swing.GroupLayout visualSelectDesignerPanelLayout = new javax.swing.GroupLayout(visualSelectDesignerPanel);
        visualSelectDesignerPanel.setLayout(visualSelectDesignerPanelLayout);
        visualSelectDesignerPanelLayout.setHorizontalGroup(
            visualSelectDesignerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        visualSelectDesignerPanelLayout.setVerticalGroup(
            visualSelectDesignerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );

        clientTabbedPane.addTab("Visual Select Designer", visualSelectDesignerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    /* Setters */
    public void setInputTextAreaString(String string) {this.commandInputOutputPanel1.setInputTextAreaString(string);}

    public void setOutputAreaString(String string) {
        this.commandInputOutputPanel1.setOutputAreaString(string);
    }

    public void setClientController(ClientController clientController) {
        this.clientController = clientController;
        this.commandPanel1.setClientController(clientController);
    }

    /* Getters */
    public String getInputAreaText() { return this.commandInputOutputPanel1.getInputAreaText(); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane clientTabbedPane;
    private frontend.center_panel.CommandInputOutputPanel commandInputOutputPanel1;
    private frontend.center_panel.CommandPanel commandPanel1;
    private javax.swing.JSplitPane sqlCommandExecutionPanel;
    private frontend.visual_designers.VisualDeleteDesigner visualDeleteDesignerPanel;
    private frontend.visual_designers.VisualInsertDesigner visualInsertDesignerPanel;
    private frontend.visual_designers.VisualSelectDesigner visualSelectDesignerPanel;
    // End of variables declaration//GEN-END:variables
}
