package frontend.center_panel;

import frontend.visual_designers.visual_elements.SQLDocument;
import lombok.Setter;

import javax.swing.text.*;
import java.awt.*;

public class CommandInputOutputPanel extends javax.swing.JPanel {
    public CommandInputOutputPanel() {
        initComponents();

        // Setting the number of tabs and their length
        TabStop[] tabs = new TabStop[100];
        for (int j = 0; j < tabs.length; j++) {
            tabs[j] = new TabStop((j + 1) * 25);
        }

        TabSet tabSet = new TabSet(tabs);

        SimpleAttributeSet attributes = new SimpleAttributeSet();
        StyleConstants.setTabSet(attributes, tabSet);
        this.inputArea.setParagraphAttributes(attributes, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandSplitPane = new javax.swing.JSplitPane();
        outputScrollPanel = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        input = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextPane();

        setMinimumSize(new java.awt.Dimension(900, 1000));
        setPreferredSize(new java.awt.Dimension(900, 900));

        commandSplitPane.setDividerLocation(450);
        commandSplitPane.setDividerSize(3);
        commandSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outputArea.setRows(5);
        outputArea.setText("COMMAND OUTPUT");
        outputScrollPanel.setViewportView(outputArea);

        commandSplitPane.setRightComponent(outputScrollPanel);

        inputArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputArea.setStyledDocument(new SQLDocument());
        input.setViewportView(inputArea);

        commandSplitPane.setLeftComponent(input);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(commandSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(commandSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /* Setters */
    public void setInputAreaFont(Font font) { this.inputArea.setFont(font); }

    public void setInputTextAreaString(String string) { this.inputArea.setText(string); }

    public void setOutputAreaString(String string) { this.outputArea.setText(string); }

    public void increaseFont() {
        Font font = this.inputArea.getFont();
        Font newFont = new Font("Segoe", Font.PLAIN, font.getSize() + 1);

        // Set size
        this.inputArea.setFont(newFont);
        this.outputArea.setFont(newFont);
    }

    public void decreaseFont() {
        Font font = this.inputArea.getFont();
        if (font.getSize() > 0) {
            Font newFont = new Font("Segoe", Font.PLAIN, font.getSize() - 1);

            // Set size
            this.inputArea.setFont(newFont);
            this.outputArea.setFont(newFont);
        }
    }

    /* Getters */
    public String getInputAreaText() { return this.inputArea.getText(); }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane commandSplitPane;
    private javax.swing.JScrollPane input;
    private javax.swing.JTextPane inputArea;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JScrollPane outputScrollPanel;
    // End of variables declaration//GEN-END:variables
}
