package frontend.project_manager;

import service.Config;
import service.Utility;

import javax.swing.*;
import java.io.File;

public class ProjectManagerPanel extends javax.swing.JPanel {

    public ProjectManagerPanel() {
        initComponents();

        this.initLabelIcons();
    }

    private void initLabelIcons() {
        // Set SQL Query Label Icon (resize it to 32x32)
        sqlQueryLabel.setIcon(Utility.resizeIcon(
                new ImageIcon(Config.getImagesPath() + File.separator + "sql_file_icon.png"),
                32, 32
        ));

        // Set Project Label Icon (resize it to 32x32)
        projectLabel.setIcon(Utility.resizeIcon(
                new ImageIcon(Config.getImagesPath() + File.separator + "sql_folder_icon.png"),
                32, 32
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectManagerTag = new javax.swing.JLabel();
        sqlQueryLabel = new javax.swing.JLabel();
        newProjectButton = new javax.swing.JButton();
        projectLabel = new javax.swing.JLabel();
        newQueryButton = new javax.swing.JButton();
        documentTreeScrollPanel = new javax.swing.JScrollPane();
        documentJTree = new javax.swing.JTree();

        projectManagerTag.setBackground(java.awt.Color.darkGray);
        projectManagerTag.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        projectManagerTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectManagerTag.setText("Project Manager");
        projectManagerTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projectManagerTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        projectManagerTag.setOpaque(true);

        newProjectButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProjectButton.setText("New Project");
        newProjectButton.setMargin(new java.awt.Insets(2, 7, 3, 7));
        newProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectButtonActionPerformed(evt);
            }
        });

        newQueryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newQueryButton.setText("New Query");
        newQueryButton.setMargin(new java.awt.Insets(2, 7, 3, 7));
        newQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newQueryButtonActionPerformed(evt);
            }
        });

        documentJTree.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        documentTreeScrollPanel.setViewportView(documentJTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectManagerTag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sqlQueryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newQueryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(documentTreeScrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projectManagerTag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newQueryButton)
                    .addComponent(newProjectButton)
                    .addComponent(sqlQueryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentTreeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProjectButtonActionPerformed

    private void newQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newQueryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newQueryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree documentJTree;
    private javax.swing.JScrollPane documentTreeScrollPanel;
    private javax.swing.JButton newProjectButton;
    private javax.swing.JButton newQueryButton;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel projectManagerTag;
    private javax.swing.JLabel sqlQueryLabel;
    // End of variables declaration//GEN-END:variables
}
