package frontend.object_explorer;

import service.CatalogManager;

import java.util.ArrayList;
import java.util.List;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class ObjectExplorerPanel extends javax.swing.JPanel {
    private DefaultMutableTreeNode databasesNode;
    private DefaultTreeModel jTreeNode;
    
    public ObjectExplorerPanel() {
        // Init variables
        this.initVariables();
        
        initComponents();
    }
    
    private void initVariables() {
        this.databasesNode = new DefaultMutableTreeNode("Databases");
        this.jTreeNode = new DefaultTreeModel(this.databasesNode);
    }

    public void updateDatabases(ArrayList<String> databaseNames) {
        this.databasesNode.removeAllChildren();

        for(final String databaseName : databaseNames) {
            this.databasesNode.add(new DefaultMutableTreeNode(databaseName));
        }

        this.jTreeNode.setRoot(this.databasesNode);
    }

    public void update() {
        // Get current databaseNames
        List<String> databaseNames = CatalogManager.getDatabaseNames();

        // Update nodes
        this.databasesNode.removeAllChildren(); // Clear the tree

        for(final String databaseName : databaseNames) {
            this.databasesNode.add(new DefaultMutableTreeNode(databaseName));
        }

        // Update the tree node
        this.jTreeNode.setRoot(this.databasesNode);
    }

    /* Setters */
    public void updateCurrentDatabase(String databaseName) {this.usingDatabaseField.setText(databaseName);}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objectExplorerTag = new javax.swing.JLabel();
        databasesPanel = new javax.swing.JPanel();
        treeScrollPanel = new javax.swing.JScrollPane();
        treeDatabases = new javax.swing.JTree();
        usingDatabaseLabel = new javax.swing.JLabel();
        usingDatabaseField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        objectExplorerTag.setBackground(java.awt.Color.darkGray);
        objectExplorerTag.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        objectExplorerTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        objectExplorerTag.setLabelFor(this);
        objectExplorerTag.setText("Object Explorer");
        objectExplorerTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        objectExplorerTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        objectExplorerTag.setOpaque(true);

        treeDatabases.setBorder(null);
        treeDatabases.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        treeDatabases.setModel(jTreeNode);
        treeDatabases.setToolTipText("");
        treeScrollPanel.setViewportView(treeDatabases);

        usingDatabaseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usingDatabaseLabel.setText("Using database:");

        usingDatabaseField.setEditable(false);
        usingDatabaseField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout databasesPanelLayout = new javax.swing.GroupLayout(databasesPanel);
        databasesPanel.setLayout(databasesPanelLayout);
        databasesPanelLayout.setHorizontalGroup(
            databasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(treeScrollPanel)
            .addGroup(databasesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usingDatabaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(usingDatabaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        databasesPanelLayout.setVerticalGroup(
            databasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasesPanelLayout.createSequentialGroup()
                .addGroup(databasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usingDatabaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(databasesPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(usingDatabaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(objectExplorerTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databasesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(objectExplorerTag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databasesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel databasesPanel;
    private javax.swing.JLabel objectExplorerTag;
    private javax.swing.JTree treeDatabases;
    private javax.swing.JScrollPane treeScrollPanel;
    private javax.swing.JTextField usingDatabaseField;
    private javax.swing.JLabel usingDatabaseLabel;
    // End of variables declaration//GEN-END:variables
}
