package frontend3.center_panel;

public class CenterClientPanel extends javax.swing.JPanel {

    public CenterClientPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientTabbedPane = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        commandPanel1 = new frontend3.center_panel.CommandPanel();
        commandInputOutputPanel1 = new frontend3.center_panel.CommandInputOutputPanel();
        visualQueryDesignerPanel = new frontend3.VisualQueryDesigner();

        clientTabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clientTabbedPane.setMinimumSize(new java.awt.Dimension(900, 900));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setTopComponent(commandPanel1);
        jSplitPane1.setRightComponent(commandInputOutputPanel1);

        clientTabbedPane.addTab("SQL Command Execution", jSplitPane1);

        javax.swing.GroupLayout visualQueryDesignerPanelLayout = new javax.swing.GroupLayout(visualQueryDesignerPanel);
        visualQueryDesignerPanel.setLayout(visualQueryDesignerPanelLayout);
        visualQueryDesignerPanelLayout.setHorizontalGroup(
            visualQueryDesignerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        visualQueryDesignerPanelLayout.setVerticalGroup(
            visualQueryDesignerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );

        clientTabbedPane.addTab("Visual Query Designer", visualQueryDesignerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane clientTabbedPane;
    private frontend3.center_panel.CommandInputOutputPanel commandInputOutputPanel1;
    private frontend3.center_panel.CommandPanel commandPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private frontend3.VisualQueryDesigner visualQueryDesignerPanel;
    // End of variables declaration//GEN-END:variables
}
