package frontend;

import control.ClientController;
import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;


@Slf4j
public class ClientFrame extends javax.swing.JFrame {
    // References
    private final ClientController clientController;

    public ClientFrame(ClientController clientController) {
        // Reference
        this.clientController = clientController;

        initComponents();

        // Set references
        this.centerClientPanel1.setClientController(this.clientController);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objectExplorerPanel1 = new frontend.object_explorer.ObjectExplorerPanel();
        centerClientPanel1 = new frontend.center_panel.CenterClientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAAP SQL Server Management Application");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(objectExplorerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerClientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(objectExplorerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(centerClientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Setters */
    public void updateDatabaseNamesTree(ArrayList<String> databaseNames) { this.objectExplorerPanel1.updateDatabases(databaseNames); }

    public void setInputTextAreaString(String string) { this.centerClientPanel1.setInputTextAreaString(string); }

    public void setOutputAreaString(String string) { this.centerClientPanel1.setOutputAreaString(string); }

    public void setCurrentDatabaseName(String databaseName) { this.objectExplorerPanel1.updateCurrentDatabase(databaseName); }

    /* Getters */
    public String getInputTextAreaString() { return this.centerClientPanel1.getInputAreaText(); }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frontend.center_panel.CenterClientPanel centerClientPanel1;
    private frontend.object_explorer.ObjectExplorerPanel objectExplorerPanel1;
    // End of variables declaration//GEN-END:variables
}
