package frontend.visual_designers.visual_select;

import service.CatalogManager;

import java.util.ArrayList;
import java.util.List;

public class SelectTableFieldsPanel extends javax.swing.JPanel {
    private final String databaseName, tableName;
    private final List<String> tableFieldsNames;

    public SelectTableFieldsPanel(String databaseName, String tableName) {
        // Table and database names
        this.databaseName = databaseName;
        this.tableName = tableName;

        // Get table details
        this.tableFieldsNames = CatalogManager.getFieldNames(this.databaseName, this.tableName);

        initComponents();

        // Initialize selectors
        this.initSelectors();
    }

    private void initSelectors() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableNameLabel = new javax.swing.JLabel();
        selectorPanel = new javax.swing.JPanel();
        selectAllBox = new javax.swing.JCheckBox();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        tableNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableNameLabel.setText("table_name");
        tableNameLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tableNameLabel.setOpaque(true);

        selectorPanel.setLayout(new java.awt.GridLayout(6, 2));

        selectAllBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAllBox.setText("* (All Fields)");
        selectorPanel.add(selectAllBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(tableNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox selectAllBox;
    private javax.swing.JPanel selectorPanel;
    private javax.swing.JLabel tableNameLabel;
    // End of variables declaration//GEN-END:variables
}
