package frontend.visual_designers.visual_select;

import lombok.Setter;
import service.CatalogManager;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;

public class SelectTablesPanel extends javax.swing.JPanel {
    private String databaseName;
    private List<String> tableNames;
    private List<JCheckBox> checkBoxes;

    // References
    private VisualSelectDesigner visualSelectDesigner;

    public SelectTablesPanel() {
        initComponents();

        // Initialize variables
        this.initVariables();
    }

    private void initVariables() {
        this.checkBoxes = new ArrayList<>();
    }

    private void updateTables() {
        this.tableNames = CatalogManager.getCurrentDatabaseTableNames(databaseName);

        Font font = this.selectAllTablesBox.getFont();

        // Empty check boxes list
        this.checkBoxes.clear();

        // Empty grid layout
        this.tablesPanel.removeAll();

        // Add back select all tables checkbox
        this.tablesPanel.add(this.selectAllTablesBox);
        for (final String tableName : this.tableNames) {
            JCheckBox checkBox = new JCheckBox(tableName);
            checkBox.setFont(font);
            checkBox.setHorizontalAlignment(JCheckBox.CENTER);
            checkBox.setBorder(new LineBorder(new Color(102, 102, 102), 3));
            checkBox.setBorderPainted(true);

            // Add listener
            checkBox.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent event) {
                    JCheckBox checkBox = (JCheckBox) event.getSource();
                    if (checkBox.isSelected()) {
                        selectAllTablesBox.setSelected(false);
                    }
                }
            });

            // Add to panel and list
            this.tablesPanel.add(checkBox);
            this.checkBoxes.add(checkBox);
        }
    }

    public void updateDatabase(String databaseName) {
        this.databaseName = databaseName;
        this.updateTables();
    }

    public void setVisualSelectDesigner(VisualSelectDesigner visualSelectDesigner) { this.visualSelectDesigner = visualSelectDesigner; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        explainerScrollPanel = new javax.swing.JScrollPane();
        explainerTextArea = new javax.swing.JTextArea();
        doneButton = new javax.swing.JButton();
        tablesPanel = new javax.swing.JPanel();
        selectAllTablesBox = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(1000, 850));

        explainerTextArea.setColumns(20);
        explainerTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        explainerTextArea.setRows(5);
        explainerTextArea.setText("Welcome to the Visual Select Designer, where we help you design your queries in a simple fasion!\n\nPlease select atleast one table before pressing the 'Done' button.\nAfter pressing the done button you will be presented with another panel, where you can choose what fields your SELECT will have\nfrom which tables, you can rename fields, add conditions to them and much more!");
        explainerScrollPanel.setViewportView(explainerTextArea);

        doneButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doneButton.setText("Done");
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                doneButtonMousePressed(evt);
            }
        });
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        tablesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablesPanel.setLayout(new java.awt.GridLayout(6, 2));

        selectAllTablesBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectAllTablesBox.setSelected(true);
        selectAllTablesBox.setText("* (Every table)");
        selectAllTablesBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        selectAllTablesBox.setBorderPainted(true);
        selectAllTablesBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectAllTablesBox.setOpaque(true);
        selectAllTablesBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectAllTablesBoxItemStateChanged(evt);
            }
        });
        tablesPanel.add(selectAllTablesBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(explainerScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(explainerScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(doneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectAllTablesBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectAllTablesBoxItemStateChanged
        // If all is selected -> Check off every other one
        if (this.selectAllTablesBox.isSelected()) {
            this.checkBoxes.forEach((checkbox) -> checkbox.setSelected(false));
        }
    }//GEN-LAST:event_selectAllTablesBoxItemStateChanged

    private void doneButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMousePressed
        // Check if 'all tables' checkbox is selected
        if (this.selectAllTablesBox.isSelected()) {
            // Pass all the table names to selector panel
            this.visualSelectDesigner.switchToSelectorPanel(this.tableNames);
        } else {
            // Iterate over all checkboxes and see which are checked
            List<String> selectedTableNames = new ArrayList<>();
            int ind = 0;
            for (final JCheckBox checkBox : this.checkBoxes) {
                // If checked -> Add table name
                if(checkBox.isSelected()) {
                    selectedTableNames.add(this.tableNames.get(ind));
                }
                ind++;
            }

            // If at least one table is selected switch
            if (selectedTableNames.size() > 0) this.visualSelectDesigner.switchToSelectorPanel(selectedTableNames);
        }
    }//GEN-LAST:event_doneButtonMousePressed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane explainerScrollPanel;
    private javax.swing.JTextArea explainerTextArea;
    private javax.swing.JCheckBox selectAllTablesBox;
    private javax.swing.JPanel tablesPanel;
    // End of variables declaration//GEN-END:variables
}
