package frontend.visual_designers.visual_select;

import java.util.ArrayList;
import java.util.List;

public class SelectMainPanel extends javax.swing.JPanel {
    private List<SelectTableFieldsPanel> tableFieldsPanels;

    public SelectMainPanel() {
        initComponents();
        
        this.initVariables();
    }

    private void initVariables() {
        this.tableFieldsPanels = new ArrayList<>();
    }

    public void update(String databaseName, List<String> tableNames) {
        // Empty current list of panels and create new ones
        this.tableFieldsPanels.clear();

        // Create new panels
        int count = 0;
        for (final String tableName : tableNames) {
            SelectTableFieldsPanel panel = new SelectTableFieldsPanel(databaseName, tableName);

            // Add to list and panel
            this.tableFieldsPanels.add(panel);
            this.tableSelectorsPanel.add(panel);
            count++;

            // A max of 6 tables are supported
            if (count >= 6) break;
        }

        this.tableSelectorsPanel.revalidate();
        this.tableSelectorsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableSelectorsPanel = new javax.swing.JPanel();
        fieldSelectorScrollPanel = new javax.swing.JScrollPane();
        fieldSelectorTable = new javax.swing.JTable();
        commandOutputScrollPanel = new javax.swing.JScrollPane();
        commandOutputTextPane = new javax.swing.JTextPane();

        tableSelectorsPanel.setLayout(new java.awt.GridLayout(2, 3));

        fieldSelectorTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldSelectorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Field Name", "Table", "Alias", "Condition"
            }
        ));
        fieldSelectorScrollPanel.setViewportView(fieldSelectorTable);

        commandOutputTextPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        commandOutputScrollPanel.setViewportView(commandOutputTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commandOutputScrollPanel)
                    .addComponent(tableSelectorsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldSelectorScrollPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableSelectorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldSelectorScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandOutputScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane commandOutputScrollPanel;
    private javax.swing.JTextPane commandOutputTextPane;
    private javax.swing.JScrollPane fieldSelectorScrollPanel;
    private javax.swing.JTable fieldSelectorTable;
    private javax.swing.JPanel tableSelectorsPanel;
    // End of variables declaration//GEN-END:variables
}
