package frontend3;

public class ObjectExplorerPanel extends javax.swing.JPanel {

    public ObjectExplorerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObjectExplorerTag = new javax.swing.JLabel();
        DatabasesPanel = new javax.swing.JPanel();
        TreeScrollPane = new javax.swing.JScrollPane();
        TreeDatabases = new javax.swing.JTree();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ObjectExplorerTag.setBackground(java.awt.Color.gray);
        ObjectExplorerTag.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ObjectExplorerTag.setLabelFor(this);
        ObjectExplorerTag.setText("Object Explorer");
        ObjectExplorerTag.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ObjectExplorerTag.setOpaque(true);

        TreeDatabases.setBorder(null);
        TreeDatabases.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TreeScrollPane.setViewportView(TreeDatabases);

        javax.swing.GroupLayout DatabasesPanelLayout = new javax.swing.GroupLayout(DatabasesPanel);
        DatabasesPanel.setLayout(DatabasesPanelLayout);
        DatabasesPanelLayout.setHorizontalGroup(
            DatabasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TreeScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        DatabasesPanelLayout.setVerticalGroup(
            DatabasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ObjectExplorerTag, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatabasesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ObjectExplorerTag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatabasesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatabasesPanel;
    private javax.swing.JLabel ObjectExplorerTag;
    private javax.swing.JTree TreeDatabases;
    private javax.swing.JScrollPane TreeScrollPane;
    // End of variables declaration//GEN-END:variables
}
